### ISSUE TITLE
Improve scraping of core courses

### ISSUE THREAD

**Issue by ashwinpra** [metakgp/gyfe#1]
- The current method of scraping core courses [`find_core_courses()`](https://github.com/metakgp/gyfe/blob/6998c2309bcfe0ba96638b1fca917b07f0d6aeb2/gyfe.py#L23) is very error-prone, and involves a bit of hardcoding
- Instead, scrape them similar to how it's done in [gyft](https://github.com/metakgp/gyft/blob/3ac7adb852810f32794bd260284fd6d7e7b10e83/gyft.py#L123-L125)
- Potentially, this could even be used to find out whether user has breadth or depth electives, and how many of each, if they do

**Comment by shikharsoni07** [comment]
I'll work on this!

**Comment by nithin-gith** [comment]
interested to work on this assign me this

**Comment by ashwinpra** [comment]
Done 👍🏼
If you have any doubts, you may ask via Slack

**Comment by ashwinpra** [comment]
@nithin-gith any updates?

**Comment by nithin-gith** [comment]
not yet will update soon..
