### ISSUE TITLE
Basic functionality to download the available courses as excel sheet

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyfe#11]
- [ ] Frontend - @Dami-18 
- [ ] Backend - @premagarwals

**Comment by Dami-18** [comment]
I would like to work on this issue

**Comment by premagarwals** [comment]
I would like to work on this.

**Comment by proffapt** [comment]
@rohan-b-84 are two people needed for this? if not he may take up other open issues.

**Comment by rohan-b-84** [comment]
Yes, Actually it requires both frontend and backend.
@Dami-18 is working on the frontend, while @premagarwals is writing the backend APIs

**Comment by proffapt** [comment]
cools

**Comment by proffapt** [comment]
@Dami-18 @premagarwals continue the work
