### ISSUE TITLE
Instead of excel sheet can provide the user the same facility there in the webapp to re-arrange in order of priority

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyfe#16]

**Comment by Dami-18** [comment]
I think it would be better to download as excel sheet. (They can view it whenever they want it, it would be handy also ) If we provide them drag and drop option for rearranging, it would be difficult to see the table especially in mobile screens when number of available electives are more. Maybe we can provide some other functionality. I might be wrong. Any suggestions for this?

**Comment by proffapt** [comment]
Yeah, I wrote it as a potential future idea. But yeah it will be really difficult to implement. can drop it as `Not Important` if someone in the future finds it interesting, they can take it up. Since it's not always about doing the easy stuff but the interesting stuff :D

**Comment by proffapt** [comment]
Also, @Dami-18 would recommend to focus on `Urgent` tasks listed in the [kanban](https://github.com/orgs/metakgp/projects/4) first.

**Comment by proffapt** [comment]
This is too much of a funky task, it's way beyond foreseeable future's scope
