### ISSUE TITLE
Web Interface for GYFE

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyfe#2]
This is the POA for developing Web App.

   - [x] #17
   - [x] #11

   
 > The webapp is to be created in this repo only, CLI and WebApp will live in harmony here - refer [this](https://github.com/metakgp/gyft/issues/105)

**Comment by Harsh-cyber005** [comment]
I will be working on the fronted for gyfe keeping in mind the above requirements.

**Comment by ashwinpra** [comment]
@Harsh-cyber005 any updates?

**Comment by Harsh-cyber005** [comment]
> @Harsh-cyber005 any updates?
> 

Still working to figure out the log in page and the transfer of data from frontend to the python file

**Comment by Harsh-cyber005** [comment]
![IMG20231013144714.jpg](https://github.com/metakgp/gyfe/assets/117888618/49bf2507-941a-457c-940e-838fc8c868d2)

I am recieving this error while running the code

**Comment by Harsh-cyber005** [comment]
> @Harsh-cyber005 any updates?
> 

.

**Comment by ashwinpra** [comment]
This error might be because you don't have any depth electives this semester, is that the case?

**Comment by Harsh-cyber005** [comment]
> This error might be because you don't have any depth electives this semester, is that the case?

![IMG20231014182104.jpg](https://github.com/metakgp/gyfe/assets/117888618/0044ae66-89bb-45b2-869e-ccc3bfd2af1a)

Now what's happening?

**Comment by ShreyaBose04** [comment]
I would like to work on this, please assign it to me

**Comment by proffapt** [comment]
Are you a student of kgp?

**Comment by ShreyaBose04** [comment]
Yes

**Comment by proffapt** [comment]
great then

**Comment by Bikram-ghuku** [comment]
Is there anyone working on this issue currently? If not can I work on  this issue?

**Comment by Dami-18** [comment]
I would also like to work on this issue

**Comment by rohan-b-84** [comment]
Interested in overseeing the progress of this project

**Comment by proffapt** [comment]
@rohan-b-84 let's close this and track upcoming problems in new issues.
