### ISSUE TITLE
No OTP in email after using `--notp` flag

### ISSUE THREAD

**Issue by Bikram-ghuku** [metakgp/gyfe#7]
![image](https://github.com/metakgp/gyfe/assets/37508038/e5147e2b-b312-4f81-9671-f83aba20db01)

Prompt for OTP but no OTP in email

Possible issue of: [iitkgp-erp-login PyPi](https://github.com/metakgp/iitkgp-erp-login-pypi)

**Comment by Dami-18** [comment]
Is anybody working on this issue? If not, I would like to work on it

**Comment by ashwinpra** [comment]
Closed by #8
